version: "3.8"
name: jchess
services:
   web:
      image : docker_desktop_page
      container_name: web
      ports: 
         - 8080:8080
      restart: always
      depends_on: 
         mongodb:
            condition: service_started
   
   mongodb:
      image : mongo
      container_name: mongodb
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
         - /src/jchess/mongodb
      ports:
         - 27017:27017
      restart: unless-stopped
   
   mongo-express:
      image: mongo-express
      restart: always
      ports: 
         - 8081:8081
      
   db: 
      image: postgres
      container_name: postgres
      volumes:
         - /src/jchess/postgres
      restart: always
      ports: 
         - 5432:5432
      environment: 
         POSTGRES_PASSWORD: doubleData
      
      
volumes: 
   data: {}

networks: 
   default:
      name: jchess_network